### 회원가입 테스트
POST http://localhost:4000/api/auth/signup/admin
Content-Type: application/json

{
  "email": "admin_dada@dada.com",
  "password": "password123!",
  "name": "다다",
  "organizationName": "다다쓰 포트폴리오"
}

### 로그인 테스트
POST http://localhost:4000/api/auth/signin
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "password123!"
}

### 로그인 테스트
POST http://localhost:4000/api/auth/signin
Content-Type: application/json

{
  "email": "agent_dada@dada.com",
  "password": "password123"
}

### 
GET http://localhost:4000/api/auth/home
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxNzkxOTI5ZS1hNTdjLTQ1NDgtYThlYy1hNmY4ZWEyNjNmM2MiLCJyb2xlIjoiQURNSU4iLCJvcmdhbml6YXRpb25JZCI6IjYyZmQ1N2MzLTkwZDctNDA3My1hMzY1LTlkZmZlMzFkNDA3YyIsImlhdCI6MTc2NjY3OTQyNywiZXhwIjoxNzY2NjgzMDI3fQ.uxayssH9nleGe6mVZuAzrdpuBVTOhewtIX9lr_iN_JQ

### 새로운 팀원 생성
POST http://localhost:4000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxNzkxOTI5ZS1hNTdjLTQ1NDgtYThlYy1hNmY4ZWEyNjNmM2MiLCJyb2xlIjoiQURNSU4iLCJvcmdhbml6YXRpb25JZCI6IjYyZmQ1N2MzLTkwZDctNDA3My1hMzY1LTlkZmZlMzFkNDA3YyIsImlhdCI6MTc2NjY3OTQyNywiZXhwIjoxNzY2NjgzMDI3fQ.uxayssH9nleGe6mVZuAzrdpuBVTOhewtIX9lr_iN_JQ
Content-Type: application/json

{
  "email": "manager1@dada.com",
  "password": "password123",
  "name": "김매니저",
  "role": "MANAGER"
}

### 회사 관리자 생성
POST http://localhost:4000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwOTljODEwZi1mNTNkLTQ1ZTAtYWRmMi1kYzFiZDYwM2YxYjciLCJyb2xlIjoiQURNSU4iLCJvcmdhbml6YXRpb25JZCI6IjIyODI4NzcyLTc3ZGUtNGFlOC1iOWFhLTQ0YTY4MmI4NDk5ZSIsImlhdCI6MTc2NjcyMjA4MywiZXhwIjoxNzY2NzI1NjgzfQ.l90suVc4tltpgry_bOLCv7zOskewIZ_V2kNVEMJCC5s
Content-Type: application/json

{
  "email": "agent_dada@dada.com",
  "password": "password123",
  "name": "포트폴리오 관리자",
  "role": "AGENT",
  "organizationId":"22828772-77de-4ae8-b9aa-44a682b8499e"
}


### 유저 status 상태 변경(ACTIVE)
PATCH http://localhost:4000/api/users/approve/4d457389-3835-4303-be11-230678611d46
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwOTljODEwZi1mNTNkLTQ1ZTAtYWRmMi1kYzFiZDYwM2YxYjciLCJyb2xlIjoiQURNSU4iLCJvcmdhbml6YXRpb25JZCI6IjIyODI4NzcyLTc3ZGUtNGFlOC1iOWFhLTQ0YTY4MmI4NDk5ZSIsImlhdCI6MTc2NjcyMjk0OCwiZXhwIjoxNzY2NzI2NTQ4fQ.Gm3Go2i12SV-E6mGtK8-4sxhaoB6OmLgQWIwlCsENMk