### 회원가입 테스트
POST http://localhost:4000/api/auth/signup/admin
Content-Type: application/json

{
  "email": "dada4dev@dev.com",
  "password": "password123!",
  "name": "다다",
  "organizationName": "devDADA"
}

### 로그인 테스트
POST http://localhost:4000/api/auth/signin
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "password123!"
}

### 로그인 테스트
POST http://localhost:4000/api/auth/signin
Content-Type: application/json

{
  "email": "agent_dada@blog.com",
  "password": "password123"
}

### 로그인 테스트
POST http://localhost:4000/api/auth/signin
Content-Type: application/json

{
  "email": "manager_dada@blog.com",
  "password": "password123"
}

### 토큰 재발급
POST http://localhost:4000/api/auth/refresh
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwZTliZTZhOS0yM2I5LTQyMTctOTU1Mi01ZjBiZjcwMTRhMzQiLCJyb2xlIjoiTUFOQUdFUiIsIm9yZ2FuaXphdGlvbklkIjoiNjJiOWVmZmMtMDRlNC00MjRjLWEwNzAtMTc3ZTcxNWU2Njg0IiwiaWF0IjoxNzY4MTkwNzk0LCJleHAiOjE3Njg3OTU1OTR9.MV6oOab1Xij737F0fCkoTkadLd8zXAM0VZHCCISzMVM


### 로그아웃
POST http://localhost:4000/api/auth/signout
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzNzQ2MmYyZC05NTM1LTQ3ODctYTI4Yy02ZjE2NzIwOWMzMTYiLCJyb2xlIjoiQUdFTlQiLCJvcmdhbml6YXRpb25JZCI6IjYyYjllZmZjLTA0ZTQtNDI0Yy1hMDcwLTE3N2U3MTVlNjY4NCIsImlhdCI6MTc2Njk5OTk4NSwiZXhwIjoxNzY3NjA0Nzg1fQ.D-u0NU_Ultlxe-zJ0nWrf0b1bTmGpSV_Vd9uhNTBpJ0

### 로그인 인증 미들웨어 통과
GET http://localhost:4000/api/auth/home
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzNzQ2MmYyZC05NTM1LTQ3ODctYTI4Yy02ZjE2NzIwOWMzMTYiLCJyb2xlIjoiQUdFTlQiLCJvcmdhbml6YXRpb25JZCI6IjYyYjllZmZjLTA0ZTQtNDI0Yy1hMDcwLTE3N2U3MTVlNjY4NCIsImlhdCI6MTc2Njk5OTg3MiwiZXhwIjoxNzY3MDAzNDcyfQ.Hn_qLkJUp-Pt5_t1GwmMfJNCMGbtkdRJ6gegx9GTCwk

### 새로운 팀원 생성
POST http://localhost:4000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwOTM5N2FmNy1iZDZjLTQ3NGEtYWZlMS1mOGE5NmUwNzY1N2MiLCJyb2xlIjoiQUdFTlQiLCJvcmdhbml6YXRpb25JZCI6IjYxNTgxMTRhLTE3ZmUtNDZmYy04NDU2LWZmYzU3ZWFkNDVlYiIsImlhdCI6MTc2Njc0MTUyMywiZXhwIjoxNzY2NzQ1MTIzfQ.6mcfeWQwWgCWkYoiApM0DjUeRcUiB2fDC8oHkMXyImY
Content-Type: application/json

{
  "email": "manager1@dada.com",
  "password": "password123",
  "name": "김매니저",
  "role": "MANAGER"
}

### 회사 관리자 생성
POST http://localhost:4000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzNzQ2MmYyZC05NTM1LTQ3ODctYTI4Yy02ZjE2NzIwOWMzMTYiLCJyb2xlIjoiQUdFTlQiLCJvcmdhbml6YXRpb25JZCI6IjYyYjllZmZjLTA0ZTQtNDI0Yy1hMDcwLTE3N2U3MTVlNjY4NCIsImlhdCI6MTc2NzYxMDIxNywiZXhwIjoxNzY3NjEzODE3fQ.54Aj5vFuc_FVjhRc9AN0xb8V1SPX8-uii0BU4OH9dmE
Content-Type: application/json

{
  "email": "portfolio@dada.com",
  "password": "password123",
  "name": "블로그 매니저",
  "role": "MANAGER",
}


### 유저 status 상태 변경(ACTIVE)
PATCH http://localhost:4000/api/users/approve/37462f2d-9535-4787-a28c-6f167209c316
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzMzYxYjFkZi1jMmRiLTRjODItYjJkZC1lODRkZjFlODEyODAiLCJyb2xlIjoiQURNSU4iLCJvcmdhbml6YXRpb25JZCI6IjJlMTMyZmNkLWJmYjUtNGViMi1iMTJjLWM4MDU2OGZjMDQyZSIsImlhdCI6MTc2NjgyNDIwMCwiZXhwIjoxNzY2ODI3ODAwfQ.uSKCkHqun3t0yK5tWtMD7Q55xIAJxIsvQnXYAcrSQl0

### 유저 정보 수정
PATCH http://localhost:4000/api/users/0b7cf430-9e86-4947-9c01-cd5077b27451
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzMzYxYjFkZi1jMmRiLTRjODItYjJkZC1lODRkZjFlODEyODAiLCJyb2xlIjoiQURNSU4iLCJvcmdhbml6YXRpb25JZCI6IjJlMTMyZmNkLWJmYjUtNGViMi1iMTJjLWM4MDU2OGZjMDQyZSIsImlhdCI6MTc2NzYyOTIxNywiZXhwIjoxNzY3NjMyODE3fQ.b46cG_G2A3Vm4Q-2SF6hgY1jNlfFvQJp4NbTdcf-7JE
Content-Type: application/json

{
  "name": "포폴다다",
  "role": "MANAGER"
}


### 유저 초대
POST http://localhost:4000/api/invitations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzMzYxYjFkZi1jMmRiLTRjODItYjJkZC1lODRkZjFlODEyODAiLCJyb2xlIjoiQURNSU4iLCJvcmdhbml6YXRpb25JZCI6IjJlMTMyZmNkLWJmYjUtNGViMi1iMTJjLWM4MDU2OGZjMDQyZSIsImlhdCI6MTc2NzcwNzk4NCwiZXhwIjoxNzY3NzExNTg0fQ.VsFso70K53rUHJ8i3wv36H4slJqJWh5cpDTapfJGb9w
Content-Type: application/json

{
  "email": "dadadadada@blog.com",
  "name": "다X5",
  "role": "MANAGER",
  "organizationId":"6158114a-17fe-46fc-8456-ffc57ead45eb"
}

### 초대 목록
GET http://localhost:4000/api/invitations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwZTliZTZhOS0yM2I5LTQyMTctOTU1Mi01ZjBiZjcwMTRhMzQiLCJyb2xlIjoiTUFOQUdFUiIsIm9yZ2FuaXphdGlvbklkIjoiNjJiOWVmZmMtMDRlNC00MjRjLWEwNzAtMTc3ZTcxNWU2Njg0IiwiaWF0IjoxNzY3NzY3NTU1LCJleHAiOjE3Njc3NzExNTV9.mwJLv3HHDdSdVpkyyKE087OyWZPuxG_bT9EoW7ryJVE

### 초대받은 유저, 링크를 타고 가입하는 상황
POST http://localhost:4000/api/auth/signup/invitation/
Content-Type: application/json

{
  "email": "invite_manager@dada.com",
  "password": "password123",
  "name": "장초대",
  "organizationId": "2e132fcd-bfb5-4eb2-b12c-c80568fc042e"
}


### 초대 정보 조회
GET http://localhost:4000/api/invitations/490e6d41-9af1-4cb8-b75e-040299442783

### 조직 생성
POST http://localhost:4000/api/organizations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzMzYxYjFkZi1jMmRiLTRjODItYjJkZC1lODRkZjFlODEyODAiLCJyb2xlIjoiQURNSU4iLCJvcmdhbml6YXRpb25JZCI6IjJlMTMyZmNkLWJmYjUtNGViMi1iMTJjLWM4MDU2OGZjMDQyZSIsImlhdCI6MTc2NjgwNzE0NCwiZXhwIjoxNzY2ODEwNzQ0fQ.O0bInzeFBCjhg3lzA_hMF4YHg1C5jBivQGDWNnJHp2o
Content-Type: application/json

{
  "name": "다다로그" // 62b9effc-04e4-424c-a070-177e715e6684
}

### 조직 목록 조회 (어드민)
GET http://localhost:4000/api/organizations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzMzYxYjFkZi1jMmRiLTRjODItYjJkZC1lODRkZjFlODEyODAiLCJyb2xlIjoiQURNSU4iLCJvcmdhbml6YXRpb25JZCI6IjJlMTMyZmNkLWJmYjUtNGViMi1iMTJjLWM4MDU2OGZjMDQyZSIsImlhdCI6MTc2Nzc4NzU4MCwiZXhwIjoxNzY3NzkxMTgwfQ.G47QD9Z-rShZYQwYJ9wqLVIex6ZOr0SWhag5b1f44wQ

### 특정 조직 정보 조회
GET http://localhost:4000/api/organizations/2e132fcd-bfb5-4eb2-b12c-c80568fc042e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzMzYxYjFkZi1jMmRiLTRjODItYjJkZC1lODRkZjFlODEyODAiLCJyb2xlIjoiQURNSU4iLCJvcmdhbml6YXRpb25JZCI6IjJlMTMyZmNkLWJmYjUtNGViMi1iMTJjLWM4MDU2OGZjMDQyZSIsImlhdCI6MTc2Nzc4NzU4MCwiZXhwIjoxNzY3NzkxMTgwfQ.G47QD9Z-rShZYQwYJ9wqLVIex6ZOr0SWhag5b1f44wQ


### 유저 목록 조회
GET http://localhost:4000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzMzYxYjFkZi1jMmRiLTRjODItYjJkZC1lODRkZjFlODEyODAiLCJyb2xlIjoiQURNSU4iLCJvcmdhbml6YXRpb25JZCI6IjJlMTMyZmNkLWJmYjUtNGViMi1iMTJjLWM4MDU2OGZjMDQyZSIsImlhdCI6MTc2NzYyOTIxNywiZXhwIjoxNzY3NjMyODE3fQ.b46cG_G2A3Vm4Q-2SF6hgY1jNlfFvQJp4NbTdcf-7JE

### 유저 목록 조회
GET http://localhost:4000/api/organizations/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwOTM5N2FmNy1iZDZjLTQ3NGEtYWZlMS1mOGE5NmUwNzY1N2MiLCJyb2xlIjoiQUdFTlQiLCJvcmdhbml6YXRpb25JZCI6IjYxNTgxMTRhLTE3ZmUtNDZmYy04NDU2LWZmYzU3ZWFkNDVlYiIsImlhdCI6MTc2NzU5NzM0MiwiZXhwIjoxNzY3NjAwOTQyfQ.x_NIdx7Ou0vqypATxO8jAC4v7ZZtUgOlfg9Hr5aEVjs

### 도메인 등록 
POST http://localhost:4000/api/domains
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzMzYxYjFkZi1jMmRiLTRjODItYjJkZC1lODRkZjFlODEyODAiLCJyb2xlIjoiQURNSU4iLCJvcmdhbml6YXRpb25JZCI6IjJlMTMyZmNkLWJmYjUtNGViMi1iMTJjLWM4MDU2OGZjMDQyZSIsImlhdCI6MTc2NjgyMzkzMCwiZXhwIjoxNzY2ODI3NTMwfQ.nqKkxcWfu5-JCP0dUR92WwcyXEDrzwIPj5MV8UgeVv4
Content-Type: application/json

{
  "domainUrl": "https://blog.naver.com",
  "targetOrgId": "62b9effc-04e4-424c-a070-177e715e6684"
}

### 조직의 도메인 리스트 확인
GET http://localhost:4000/api/domains
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzMzYxYjFkZi1jMmRiLTRjODItYjJkZC1lODRkZjFlODEyODAiLCJyb2xlIjoiQURNSU4iLCJvcmdhbml6YXRpb25JZCI6IjJlMTMyZmNkLWJmYjUtNGViMi1iMTJjLWM4MDU2OGZjMDQyZSIsImlhdCI6MTc2Njg0NDE4MSwiZXhwIjoxNzY2ODQ3NzgxfQ.Xg-HHvxVTIwHJXyKADJ2H7UDhfOHTSo4Beq7gdqt538

### 도메인 삭제 
DELETE http://localhost:4000/api/domains/be6370a2-482d-481f-8ef2-4ec92a126458
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzNzQ2MmYyZC05NTM1LTQ3ODctYTI4Yy02ZjE2NzIwOWMzMTYiLCJyb2xlIjoiQUdFTlQiLCJvcmdhbml6YXRpb25JZCI6IjYyYjllZmZjLTA0ZTQtNDI0Yy1hMDcwLTE3N2U3MTVlNjY4NCIsImlhdCI6MTc2NjgyNDQ1NSwiZXhwIjoxNzY2ODI4MDU1fQ.2uQ_9kJnScMPtKz5hrXUvQv9AwvU5vHAs5Rd2olIhc8

### 도메인 상태 변경
PATCH http://localhost:4000/api/domains/a01922af-061e-4fff-accd-e6f9e845db50
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzMzYxYjFkZi1jMmRiLTRjODItYjJkZC1lODRkZjFlODEyODAiLCJyb2xlIjoiQURNSU4iLCJvcmdhbml6YXRpb25JZCI6IjJlMTMyZmNkLWJmYjUtNGViMi1iMTJjLWM4MDU2OGZjMDQyZSIsImlhdCI6MTc2Njg0NDE4MSwiZXhwIjoxNzY2ODQ3NzgxfQ.Xg-HHvxVTIwHJXyKADJ2H7UDhfOHTSo4Beq7gdqt538

### 위젯 사용 여부 확인
GET  http://localhost:4000/api/widget/config
x-site-key: e5a76b7c-58f4-4f82-af5a-4047e2fcca4e
Content-Type: application/json

### 위젯 채팅 시작
POST http://localhost:4000/api/widget/init
x-site-key: e5a76b7c-58f4-4f82-af5a-4047e2fcca4e
Content-Type: application/json

{
  "email": "gd.honggg@test.com",
  "name": "홍길동"
}

### 위젯, conversationId 메세지 목록조회
GET  http://localhost:4000/api/widget/16d0ea8a-0c39-4dc1-8b93-53a57acdd772
x-site-key: 67cf9dd7-564a-4f89-a038-95c89230a66f
Content-Type: application/json


### 위젯, 메시지 보내기
POST http://localhost:4000/api/widget/16d0ea8a-0c39-4dc1-8b93-53a57acdd772/message
x-site-key: 67cf9dd7-564a-4f89-a038-95c89230a66f
Content-Type: application/json

{
  "visitorId": "2edfea0e-31cc-4b15-897f-3a565ab9b2e6",
  "content": "안녕하세요! 문의사항이 있습니다."
}

### 사용자, 메세지 보내기
POST http://localhost:4000/api/chat/messages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzNzQ2MmYyZC05NTM1LTQ3ODctYTI4Yy02ZjE2NzIwOWMzMTYiLCJyb2xlIjoiQUdFTlQiLCJvcmdhbml6YXRpb25JZCI6IjYyYjllZmZjLTA0ZTQtNDI0Yy1hMDcwLTE3N2U3MTVlNjY4NCIsImlhdCI6MTc2Nzk1MjQ2NywiZXhwIjoxNzY3OTU0MjY3fQ.g3xXH-R7ggfkFMxHdEol8h2qdaeFdFXMl5bSOQ7IMkY
Content-Type: application/json

{
  "conversationId": "ae0b527b-c81d-48fe-ada5-fe406e6f1872",
  "content": "말씀해주신 문제가 해결되셨나요??"
}


### 특정 조직의 대화 목록 조회
GET http://localhost:4000/api/chat/conversations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzNzQ2MmYyZC05NTM1LTQ3ODctYTI4Yy02ZjE2NzIwOWMzMTYiLCJyb2xlIjoiQUdFTlQiLCJvcmdhbml6YXRpb25JZCI6IjYyYjllZmZjLTA0ZTQtNDI0Yy1hMDcwLTE3N2U3MTVlNjY4NCIsImlhdCI6MTc2Nzg4NDMwOSwiZXhwIjoxNzY3ODg2MTA5fQ.mtFX0NOxEDyCLxkp0RQo4g_iqBL3qc-K1lbtrELCLcg

### (어드민) 특정 조직의 대화 목록 조회
GET http://localhost:4000/api/chat/conversations?orgId={{조직_UUID}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzNzQ2MmYyZC05NTM1LTQ3ODctYTI4Yy02ZjE2NzIwOWMzMTYiLCJyb2xlIjoiQUdFTlQiLCJvcmdhbml6YXRpb25JZCI6IjYyYjllZmZjLTA0ZTQtNDI0Yy1hMDcwLTE3N2U3MTVlNjY4NCIsImlhdCI6MTc2Njg5NTc5NCwiZXhwIjoxNzY2ODk5Mzk0fQ.i-t5T6CqdDt1irnR3PnOLINQvjtbe3L5geL9V60b0XM

### 특정 채팅방 , 메시지 내역 조회
GET http://localhost:4000/api/chat/conversations/ae0b527b-c81d-48fe-ada5-fe406e6f1872
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzNzQ2MmYyZC05NTM1LTQ3ODctYTI4Yy02ZjE2NzIwOWMzMTYiLCJyb2xlIjoiQUdFTlQiLCJvcmdhbml6YXRpb25JZCI6IjYyYjllZmZjLTA0ZTQtNDI0Yy1hMDcwLTE3N2U3MTVlNjY4NCIsImlhdCI6MTc2Nzk2Mjc2NywiZXhwIjoxNzY3OTY0NTY3fQ.ov9nkF9h0Ck9lDaV7jUl449vSvDC_fwe1Zalb6fzaPw

### 특정 채팅방, 상태 변경
PATCH http://localhost:4000/api/chat/conversations/ae0b527b-c81d-48fe-ada5-fe406e6f1872/status
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzNzQ2MmYyZC05NTM1LTQ3ODctYTI4Yy02ZjE2NzIwOWMzMTYiLCJyb2xlIjoiQUdFTlQiLCJvcmdhbml6YXRpb25JZCI6IjYyYjllZmZjLTA0ZTQtNDI0Yy1hMDcwLTE3N2U3MTVlNjY4NCIsImlhdCI6MTc2Nzk1Njc3OCwiZXhwIjoxNzY3OTU4NTc4fQ.hYtMX7npuLF1E_z32fizbpVSHYGk03Zf3K5MtT6q8m0
Content-Type: application/json

{
  "status": "CLOSED"
}

### 특정 채팅방, 메세지 읽음 상태 변경
POST http://localhost:4000/api/chat/conversations/ae0b527b-c81d-48fe-ada5-fe406e6f1872/read
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzNzQ2MmYyZC05NTM1LTQ3ODctYTI4Yy02ZjE2NzIwOWMzMTYiLCJyb2xlIjoiQUdFTlQiLCJvcmdhbml6YXRpb25JZCI6IjYyYjllZmZjLTA0ZTQtNDI0Yy1hMDcwLTE3N2U3MTVlNjY4NCIsImlhdCI6MTc2NzkzNjUzMCwiZXhwIjoxNzY3OTM4MzMwfQ.bERM7H26gFfM8UyX4TL2ZtzqUs2uYKXL-1OMiaxPX90
Content-Type: application/json
